[package]
name = "mycelium"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
atty = "0.2"

[dev-dependencies]
rand = "0.8"